### ISSUE TITLE
Make Folders

### ISSUE THREAD

**Issue by chayan-chawra-1903** [chayan-chawra-1903/HacktoberFest-2021#1]
@Chayan-19 Please make folders for different programming languages.

**Comment by chetan639** [comment]
Can I make these folders and add some code of mine?

**Comment by chayan-chawra-1903** [comment]
> Can I make these folders and add some code of mine?

Hi @chetan639, please wait for the initial folders to be made, and then you can surely add the code.

**Comment by Chayan-19** [comment]
> Can I make these folders and add some code of mine?

Hey, @chetan639 glad to see that you want to contribute. I've made the folders for programming languages. You can add the code to those folders. Alternatively, if you don't see your favourite programming language, feel free to make folders and add your code to them.

**Comment by Chayan-19** [comment]
@chayan-chawra-1903 please split the issue into 2 parts, one for languages and one for coding platforms.

**Comment by chayan-chawra-1903** [comment]
I've edited this issue and will be adding a new one. Closing this one as the initial folders have been made.
