### ISSUE TITLE
Add folders for different coding platforms.

### ISSUE THREAD

**Issue by chayan-chawra-1903** [chayan-chawra-1903/HacktoberFest-2021#3]
Add folders for coding platforms like `Hackerrank`, `Leetcode` etc. and follow the [Contributing Guidelines](https://github.com/chayan-chawra-1903/HacktoberFest-2021#readme)

**Comment by mrvishalsharma** [comment]
can i work on this issue can you assinge me this task to create coding platform like Hackerrank,leetcode and i can also provide you the solution of these platform
