### ISSUE TITLE
How about adding dynamic badges to readme of repo?

### ISSUE THREAD

**Issue by Chayan-19** [chayan-chawra-1903/HacktoberFest-2021#6]
I was thinking of adding dynamic badges that show the issue count, PR count, etc. Something like this:

![image](https://user-images.githubusercontent.com/55481820/135606600-aaa7bd90-1f47-48c1-894a-6674048e5799.png)

Also thinking of adding some more rules to stop spam.
@chayan-chawra-1903, let me know what do you think.

**Comment by chayan-chawra-1903** [comment]
Good idea, I'm adding the `hacktoberfest` badge to this as well.

**Comment by Stig124** [comment]
Can I work on that?

**Comment by chayan-chawra-1903** [comment]
> Can I work on that?

Hi @Stig124. Actually @Chayan-19 is working on this issue right now.
There is also one more open issue that can be found ![here](https://github.com/chayan-chawra-1903/HacktoberFest-2021/issues/3). You can definitely wrok on this issue.
Alternativelty if you have other suggestions or improvements for this repo, you can go ahead and open a new issue.

**Comment by chayan-chawra-1903** [comment]
Closing this issue as the changes have been made.
